### ISSUE TITLE
Error with script

### ISSUE THREAD

**Issue by Bidmaster777** [XternA/packetshare-reward#1]
Hello, I get error when trying to claim:

An error occurred: locator.innerText: Timeout 30000ms exceeded.
 - waiting for locator('.income_price').first()
 - ---------- Packetshare Reward Auto Claim ----------

Starting login process...

Turns in a constant loop, but does not claim.

**Comment by XternA** [comment]
Hello. I'm actually aware of this issue already, just I haven't had the time to make the changes to reflect this. The reason for the issue is that the website has changed something, hence the automation is unable to proceed. 

You don't need to do anything, one an update image has been pushed from my side, your app will auto update to the new version as long as you just leave it running as is.

**Comment by Bidmaster777** [comment]
Hi thx for you reply! I will just wait for an updated version then ;-) Thanks in advance!

**Comment by XternA** [comment]
Thanks for your patience.

**Comment by XternA** [comment]
Update has been pushed to fix the changes to the current balance causing the issue. 

Update should be automatically pulled within 2 hours of your watchtower schedule. To force the update immediately, kindly redeploy the `Packetshare` service only.

**Comment by Bidmaster777** [comment]
Wow, that was fast! Thanks! I'll try ;-)

**Comment by XternA** [comment]
I've got a bit of time now and luckily then change on the website code was really minor hence the quick update haha. 

Anyways, enjoy!

**Comment by Bidmaster777** [comment]
I just manually updated and it works!! Thanks ;-)
